### PR TITLE
chore. updateFields compatibility with php 7 and 8

### PR DESCRIPTION
**Pull request by pangolp**
I need someone to test this, because I don't know if it will work. I don't use this product at the moment, so I don't have a local version to test.

- Closes https://github.com/azerothcore/aowow/issues/40

### CODE REVIEW

**Comment by pangolp** [comment]
Perhaps the version check should be done outside the foreach, because it will check the version several times and checking it once would be more than enough.

**Comment by pangolp** [comment]
@Sarjuuk Could you give me some feedback on this change? Thanks.

**Comment by Sarjuuk** [comment]
ffs merge, you are 250+ commits behind!
https://github.com/Sarjuuk/aowow/commit/d16b08bb297dd1522040a01d1ba8958fba52d155 fixed that


Or just always cast to float. Why would you differentiate between versions?

**Comment by pangolp** [comment]
> ffs merge, you are 250+ commits behind!
> https://github.com/Sarjuuk/aowow/commit/d16b08bb297dd1522040a01d1ba8958fba52d155 fixed that
> 
> 
> Or just always cast to float. Why would you differentiate between versions?

It was an issue they opened. The truth is not. Just look for the solution and I shared it. The repository should then be updated first or directly archived and worked with the dream.

**Comment by Helias** [comment]
> ffs merge, you are 250+ commits behind! [Sarjuuk@d16b08b]

I know 😢  https://github.com/azerothcore/aowow/issues/47

I will do it when I'll have more time

**Comment by pangolp** [comment]
I think we should close this issue then and update the repository.

**Pull request closed without merging**
